const categories = [
  // Categorias e modalidades mais gerais
  { value: 'agricultura', label: 'Agricultura' },
  { value: 'jardinagem', label: 'Jardinagem' },
  { value: 'animais', label: 'Animais' },
  { value: 'beleza', label: 'Beleza' },
  { value: 'casa', label: 'Casa' },
  { value: 'construcao', label: 'Construção' },
  { value: 'decoracao', label: 'Decoração' },
  { value: 'comunicacao', label: 'Comunicação' },
  { value: 'artes-visuais', label: 'Artes Visuais' },
  { value: 'festas', label: 'Festas' },
  { value: 'eventos', label: 'Eventos' },
  { value: 'ensino', label: 'Ensino' },
  { value: 'moda', label: 'Moda' },
  { value: 'saude', label: 'Saúde' },
  { value: 'esportes', label: 'Esportes' },
  { value: 'telefonia', label: 'Telefonia' },
  { value: 'informatica', label: 'Informática' },
  { value: 'variedades', label: 'Variedades' },
  { value: 'veiculos', label: 'Veículos' },
  { value: 'viagem', label: 'Viagem' },
  { value: 'turismo', label: 'Turismo' },
  { value: 'outros-servicos', label: 'Outros Serviços' },
  // Serviços mais específicos
  { value: 'ferramentas', label: 'Ferramentas' },
  { value: 'produtos-agricolas', label: 'Produtos Agrícolas' },
  { value: 'servicos-de-poda', label: 'Serviços de poda' },
  { value: 'jardinagem', label: 'Jardinagem' },
  { value: 'acogue', label: 'Açogue' },
  { value: 'frigorifico', label: 'Frigorífico' },
  { value: 'bar', label: 'Bar' },
  { value: 'bolos', label: 'Bolos' },
  { value: 'doces', label: 'Doces' },
  { value: 'tortas', label: 'Tortas' },
  { value: 'bomboniere', label: 'Bomboniere' },
  { value: 'buffet', label: 'Buffet' },
  { value: 'cestas-para-cafe-da-manha', label: 'Cestas para café da manhã' },
  { value: 'cozinheiro(a)', label: 'Cozinheiro(a)' },
  { value: 'distribuidor-de-agua', label: 'Distribuidor de água' },
  { value: 'conveniencia', label: 'Conveniência' },
  { value: 'bebidas-em-geral', label: 'Bebidas em geral' },
  { value: 'espetinhos', label: 'Espetinhos' },
  { value: 'hamburgueria', label: 'Hamburgueria' },
  { value: 'hortifruti', label: 'Hortifruti' },
  { value: 'lanches-e-salgados', label: 'Lanches e salgados' },
  { value: 'marmitas', label: 'Marmitas' },
  { value: 'quentinhas', label: 'Quentinhas' },
  { value: 'padaria', label: 'Padaria' },
  { value: 'pescados', label: 'Pescados' },
  { value: 'pizzaria', label: 'Pizzaria' },
  { value: 'polpas-de-fruta', label: 'Polpas de fruta' },
  { value: 'produtos-naturais', label: 'Produtos naturais' },
  { value: 'organicos', label: 'Orgânicos' },
  { value: 'queijeiro(a)', label: 'Queijeiro(a)' },
  { value: 'mantegueiro(a)', label: 'Mantegueiro(a)' },
  { value: 'quiosque', label: 'Quiosque' },
  { value: 'restaurante', label: 'Restaurante' },
  { value: 'soverteria', label: 'Sorveteria' },
  { value: 'açaiteria', label: 'Açaiteria' },
  { value: 'supermercado', label: 'Supermercado' },
  { value: 'mini-box', label: 'Mini-box' },
  { value: 'suplementos-alimentares', label: 'Suplementos alimentares' },
  {
    value: 'banho-de-animais-domesticos',
    label: 'Banho de animais domésticos',
  },
  { value: 'tosa-de-animais-domesticos', label: 'Tosa de animais domésticos' },
  { value: 'clinica-veterinaria', label: 'Clínica Veterinária' },
  { value: 'pet-shop', label: 'Pet Shop' },
  { value: 'racao', label: 'Ração' },
  { value: 'barbearia', label: 'Barbearia' },
  { value: 'cabeleireiro(a)', label: 'Cabeleireiro(a)' },
  { value: 'depilacao', label: 'Depilação' },
  { value: 'designer-de-sobrancelhas', label: 'Designer de sobrancelhas' },
  { value: 'estetica', label: 'Estética' },
  { value: 'manicure', label: 'Manicure' },
  { value: 'peticure', label: 'Peticure' },
  { value: 'maquiador(a)', label: 'Maquiador(a)' },
  { value: 'perfumaria', label: 'Perfumaria' },
  { value: 'cosmeticos', label: 'Cosméticos' },
  { value: 'produtos-de-beleza', label: 'Produtos de beleza' },
  {
    value: 'artigos-de-cama-mesa-e-banho',
    label: 'Artigos de cama mesa e banho',
  },
  { value: 'carpinteiro', label: 'Carpinteiro' },
  { value: 'ceramica', label: 'Cerâmica' },
  { value: 'chaveiro', label: 'Chaveiro' },
  { value: 'decoracao', label: 'Decoração' },
  {
    value: 'distribuidor-de-gas-de-cozinha',
    label: 'Distribuidor de gás de cozinha',
  },
  { value: 'eletricista', label: 'Eletricista' },
  { value: 'eletrodomesticos', label: 'Eletrodomésticos' },
  { value: 'eletroeletronicos', label: 'Eletroeletrônicos' },
  { value: 'encanador', label: 'Encanador' },
  { value: 'estofador', label: 'Estofador' },
  { value: 'ferreiro', label: 'Ferreiro' },
  { value: 'gesseiro', label: 'Gesseiro' },
  {
    value: 'instalacao-de-antenas-de-tv',
    label: 'Instalação de antenas de TV',
  },
  {
    value: 'lavador(a)-de-colchoes-e-estofados',
    label: 'Lavador(a) de colchões e estofados',
  },
  { value: 'madeireira', label: 'Madeireira' },
  {
    value: 'manutencao-de-eletrodomesticos',
    label: 'Manutenção de eletrodomésticos',
  },
  { value: 'marceneiro', label: 'Marceneiro' },
  { value: 'material-de-construcao', label: 'Material de construção' },
  { value: 'material-eletrico', label: 'Material elétrico' },
  { value: 'hidraulico', label: 'Hidráulico' },
  { value: 'movelaria', label: 'Movelaria' },
  { value: 'montador-de-moveis', label: 'Montador de móveis' },
  { value: 'pedreiro', label: 'Pedreiro' },
  { value: 'pintor-de-parede', label: 'Pintos de parede' },
  { value: 'produtos-de-limpeza', label: 'Produtos de limpeza' },
  {
    value: 'reparo-de-maquinas-e-aparelhos-de-refrigeracao',
    label: 'Reparo de máquinas e aparelhos de refrigeração',
  },
  { value: 'serralharia', label: 'Serralharia' },
  { value: 'vidracaria', label: 'Vidraçaria' },
  { value: 'artista-plastico', label: 'Artista plástico' },
  { value: 'designer-grafico', label: 'Designer gráfico' },
  { value: 'editor-de-jornais', label: 'Editor de jornais' },
  { value: 'assessor(a)-de-imprensa', label: 'Assessor(a) de imprensa' },
  { value: 'editor(a)-de-videos', label: 'Editor(a) de vídeos' },
  { value: 'fotografo(a)', label: 'Fotografo(a)' },
  { value: 'freelancer', label: 'Freelancer' },
  { value: 'grafica', label: 'Gráfica' },
  { value: 'impressao-digital', label: 'Impressão digital' },
  { value: 'locutor(a)', label: 'Locutor(a)' },
  { value: 'manutencao-de-tv', label: 'Manutenção de TV' },
  { value: 'manutencao-de-radio', label: 'Manutenção de rádio' },
  { value: 'manutencao-de-som', label: 'Manutenção de som' },
  {
    value: 'produtor(a)-de-conteudo-digital',
    label: 'Produtor(a) de conteúdo digital',
  },
  { value: 'serigrafia', label: 'Serigrafia' },
  { value: 'servicos-de-marketing', label: 'Servios de marketing' },
  { value: 'web-designer', label: 'Web designer' },
  { value: 'animador-de-festa-infantil', label: 'Animador de festa infantil' },
  { value: 'artigos-para-festas', label: 'Artigos para festas' },
  { value: 'cantor(a)', label: 'Cantor(a)' },
  { value: 'banda-musical', label: 'Banda Musical' },
  { value: 'instrumentista', label: 'Instrumentista' },
  { value: 'musicista', label: 'Musicista' },
  { value: 'salao-de-festas', label: 'Salão de festas' },
  { value: 'salao-de-jogos', label: 'Salão de jogos' },
  {
    value: 'instrutor(a)-de-cursos-preparatorios',
    label: 'Instrutor(a) de cursos preparatórios',
  },
  { value: 'instrutor(a)-de-danca', label: 'Instrutor(a) de dança' },
  { value: 'instrutor(a)-de-musica', label: 'Instrutor(a) de música' },
  { value: 'professor(a)-particular', label: 'Professor(a) particular' },
  {
    value: 'revisor(a)-de-trabalhos-academicos',
    label: 'Revisor(a) de trabalhos acadêmicos',
  },
  {
    value: 'aluguel-de-vestuario-social',
    label: 'Aluguel de vestuário social',
  },
  { value: 'bijuterias', label: 'Bijuterias' },
  { value: 'joias-e-semi-joias', label: 'Jóias e semi-jóias' },
  { value: 'bolsas-e-acessorios', label: 'Bolsas e acessórios' },
  { value: 'calcados', label: 'Calçados' },
  { value: 'costureira', label: 'Costureira' },
  { value: 'relojoeiro(a)', label: 'Relojoeiro(a)' },
  {
    value: 'roupas-intimas-e-acessorios',
    label: 'Roupas íntimas e acessórios',
  },
  { value: 'sapateiro(a)', label: 'Sapateiro(a)' },
  { value: 'tecidos-e-aviamentos', label: 'Tecidos e aviamentos' },
  { value: 'vestuario-e-acessorios', label: 'Vestuário e acessórios' },
  { value: 'academia', label: 'Academia' },
  { value: 'artigos-esportivos', label: 'Artigos esportivos' },
  { value: 'clinica-medica', label: 'Clínica Médica' },
  { value: 'clinica-odontologica', label: 'Clínica Odontológica' },
  { value: 'farmacia', label: 'Farmácia' },
  {
    value: 'laboratorio-de-analises-clinicas',
    label: 'Laboratório de análises clínicas',
  },
  { value: 'otica', label: 'Ótica' },
  { value: 'profissional-de-saude', label: 'Profissional de saúde' },
  {
    value: 'servicos-de-protese-dentaria',
    label: 'Serviços de prótese dentária',
  },
  { value: 'celular-e-acessorios', label: 'Celular e acessórios' },
  { value: 'lan-house', label: 'Lan House' },
  { value: 'manutencao-de-celular', label: 'Manutenção de celular' },
  { value: 'manutencao-de-computador', label: 'Manutenção de computador' },
  { value: 'suprimentos-de-informatica', label: 'Suprimentos de informática' },
  { value: 'artesanato', label: 'Artesanato' },
  {
    value: 'artigos-de-papelaria-e-escritorio',
    label: 'Artigos de papelaria e escritório',
  },
  {
    value: 'brinquedos-e-artigos-infantis',
    label: 'Brinquedos e artigos infantis',
  },
  { value: 'loja-de-variedades', label: 'Loja de variedades' },
  { value: 'promotor(a)-de-vendas', label: 'Promotor(a) de vendas' },
  { value: 'utilidades-domesticas', label: 'Utilidades domésticas' },
  { value: 'adesivagem', label: 'Adesivagem' },
  { value: 'bicicletas', label: 'Bicicletas' },
  { value: 'borracharia', label: 'Borracharia' },
  { value: 'caminhoneiro(a)', label: 'Caminhoneiro(a)' },
  { value: 'funileiro', label: 'Funileiro' },
  { value: 'lanterneiro', label: 'Lanterneiro' },
  { value: 'lava-a-jato', label: 'Lava a jato' },
  { value: 'moto-taxi', label: 'Moto-táxi' },
  { value: 'oficina-mecanica', label: 'Oficina mecânica' },
  {
    value: 'pecas-e-acessorios-para-veiculos',
    label: 'Peças e acessórios para veículos',
  },
  { value: 'pintor-de-veiculos', label: 'Pintor de veículos' },
  { value: 'posto-de-combustivel', label: 'Posto de combustível' },
  { value: 'taxi', label: 'Táxi' },
  { value: 'transportador-de-mudancas', label: 'Transportador de mudanças' },
  { value: 'transporte-alternativo', label: 'Transporte alternativo' },
  { value: 'transporte-escolar', label: 'Transporte escolar' },
  { value: 'aluguel-de-veiculos', label: 'Aluguel de veículos' },
  { value: 'guia-turistico', label: 'Guia turístico' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'malas-e-artigos-de-viagem', label: 'Malas e artigos de viagem' },
  { value: 'pousada', label: 'Pousada' },
  { value: 'restaurante', label: 'Restaurante' },
  { value: 'certificadora', label: 'Certificadora' },
  { value: 'escritorio-de-advocacia', label: 'Escritório de advocacia' },
  {
    value: 'escritorio-de-contabilidade',
    label: 'Escritório de contabilidade',
  },
];

export default categories;
